routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index');
/** Dashboard */
require(__DIR__ . DIRECTORY_SEPARATOR . 'web' .DIRECTORY_SEPARATOR . 'admin' . DIRECTORY_SEPARATOR . 'index.php');

Route::get('/search', 'SearchController@index')->name('search');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/conversations', 'ConversationsController@index')->name('conversations');

Route::group(['namespace' => 'Auth'], function () {

    // Admin Invitation
    Route::get('invite', 'AdmininviteController@invite')->name('invite');
    Route::post('invite', 'AdmininviteController@process')->name('process');

    // {token} is a required parameter that will be exposed to us in the controller method
    Route::get('accept/{token}', 'AdmininviteController@accept')->name('accept');

    // Social Auth
    Route::get('oauth/{driver}', 'SocialAuthController@redirectToProvider')->name('social.oauth');
    Route::get('oauth/{driver}/callback', 'SocialAuthController@handleProviderCallback')->name('social.callback');

});

Route::group(['middleware' => 'web'], function () {

    //User Profile
    Route::get('/profiles/users', 'MyaccountController@usersfollow');
    Route::post('/profiles/toggle', 'MyaccountController@toggle');

    //Logout User
    Route::get('user/logout', 'Auth\LoginController@UserLogout')->name('user.logout');

});


Route::get('invitations/{invitation_id}/{action}', 'Api\AcceptController@accept')->name('invitations.send');

//User
Auth::routes(['verify' => true]);
Route::group(['namespace' => 'User'], function () {

    //Conditions utilisation Routes
    Route::get('/terms_conditions/', 'ConditionController@index');

    //Presentation Route
    Route::get('presentation/{presentation}', 'PresentationController@presentation')->name('presentation');

    //Orders Route
    Route::get('orders', 'OrdersController@index')->name('orders');

    //Faqs Route
    Route::get('faqs', 'FaqsController@index')->name('faqs');
    Route::get('faqs/topics/{category}', 'FaqsController@categoryfaq')->name('category_faq');

    //Evenements Route
    Route::get('/evenements', 'EvenementsController@index')->name('evenements');

    //Others (autres services) Route
    Route::get('others', 'OthersController@index')->name('others');

    //Testimonials Route
   // Route::get('testimonial', 'TestimonialControlle@index')->name('testimonial');

    //About Us Route
    Route::get('about', 'AboutController@index')->name('about-us');

    //Work with Us Route
    Route::post('/save-work', 'AboutController@save_work')->name('user.save_work');

    //Events Route
    Route::get('topic/events', 'EventsController@index')->name('events');
    Route::get('topic/events/{event}', 'EventsController@event')->name('topic.events');
    Route::get('topics/{category}', 'EventsController@category')->name('topic.category');
    Route::get('topics/tag/{tag}', 'EventsController@tag')->name('topic.tag');

    //Articles Route
    Route::get('topic/articles', 'ArticlesController@index')->name('articles');
    Route::get('topic/articles/{article}', 'ArticlesController@article')->name('topic.articles');
    Route::get('topics/{category}', 'ArticlesController@category')->name('topic.category');
    Route::get('topics/tag/{tag}', 'ArticlesController@tag')->name('topic.tag');

    //Cookies Informations Site Route
    Route::get('/cookies-site', 'CookiesinformationsController@user')->name('user.cookies');
    Route::resource('admin/cookies-site','CookiesinformationsController');
    Route::get('/admin/cookies-site/lm/{cookie}', 'CookiesinformationsController@vector')->name('cookies-site.view');
    Route::get('/admin/cookies-site/view/{slug}', 'CookiesinformationsController@view');
    Route::get('/admin/api/cookies-site', 'CookiesinformationsController@api');
    Route::get('/admin/change_status_cookies/{id}', 'CookiesinformationsController@disable');

    //Concept Site (d'Exposition articles) Route
    Route::get('/our_concept', 'LegalmentionpagesController@concept_page')->name('concept');

    //How to register Route
    Route::get('/how_to_register', 'LegalmentionpagesController@registration_info_page')->name('user.registration');

    //Informations Site Route
    Route::get('/informations', 'LegalmentionpagesController@information_page')->name('user.informations');

    // Site Plan Route
    Route::get('/site_plan', 'SiteplanController@index')->name('site.plan');

    // Blog Route
    Route::get('/blog', 'BlogController@index')->name('blog');

    //Mention Légales Site Route
    Route::get('/legal_notice', 'LegalmentionpagesController@legal_notice_page')->name('legal_notice');

    //Licenses Site Route
    Route::get('/licenses', 'LegalmentionpagesController@licence_page')->name('site.licences');

    //Politiques Privacy Site Route
    Route::get('/policy_privacy', 'LegalmentionpagesController@policy_privacy_page')->name('user.privacy');


    Route::post('ajaxRequest', 'EventsController@ajaxRequest')->name('ajaxRequest');

    //Route::get('product/like/{id}', ['as' => 'product.like', 'uses' => 'LikeController@likeProduct']);
    // Route::get('event/like/{id}', ['as' => 'event.like', 'uses' => 'LikeController@likeEvent']);


    //Route::get('topic/events/tag/{tag}','BlogController@tag')->name('tag');
    //Route::get('to/category/{category}','BlogController@category')->name('category');



    Route::resource('admin/messages', 'MessageController');
    Route::get('admin/messages/msg/{message}', 'MessageController@message')->name('messages.view');
    Route::get('/admin/messages/view/{slug}', 'MessageController@view');
    Route::get('admin/api/messages', 'MessageController@api');
    Route::get('admin/messages/m/send', 'MessageController@send')->name('messages.send');
    Route::get('/messages/red_confirm/{id}', 'MessageController@active');
    Route::get('/messages/discard_red/{slug}', 'MessageController@disable');


});


// API
Route::group(['namespace' => 'Api'], function () {

    Route::resource('/newsletter', 'NewsletterController');

    //Route Contact Us
    Route::get('/contact-us', 'ContactController@create')->name('contact_us');
    Route::post('/contact-us/save', 'ContactController@store')->name('contact.store');

    //Route Assistance Messages
    Route::resource('admin/demande/contact/assistance/all-assistance', 'AidecontactmessagesController');
    Route::get('admin/api/demande/contact/assistance/all-assistance', 'AidecontactmessagesController@api');
    Route::get('admin/demande/contact/assistance/active_all-assistance/{id}', 'AidecontactmessagesController@active');
    Route::get('admin/demande/contact/assistance/disable_all-assistance/{id}', 'AidecontactmessagesController@disable');
    Route::get('/aide_contact_messages', 'AidecontactmessagesController@create')->name('aide_contact_messages');
    Route::get('aide_contact_messages/contact_themes', 'AidecontactmessagesController@themes');
    Route::get('aide_contact_messages/contact_demandes', 'AidecontactmessagesController@demandes');
    Route::post('aide_contact_messages/save', 'AidecontactmessagesController@store');
});

//Reset password
Route::get('user/change_password', 'Admin\Account\ChangePasswordController@showChangePasswordFormUser')->name('user.change_password');

//POST Subscribe Route
Route::post('/subscribe_email', 'Admin\Partials\NewletterSubscribeController@store')->name('newlettersubscribe');

//Route Site
Route::group(['namespace' => 'Site','middleware' => 'web'], function () {

    //Ici sont les routes qui sont les categories Orders
    Route::group(['namespace' => 'Order'], function () {

        //Get Beautes Admin
        Route::get('/admin/orders/beautes', 'BeauteController@dashboard')->name('admin.beaute');
        Route::get('api/admin/orders/beautes', 'BeauteController@getbeautedashboard');
        Route::get('/api/orders/admin/active_beautes/{id}', 'BeauteController@adminactive');
        Route::get('/api/orders/admin/disable_beautes/{id}', 'BeauteController@admindisable');

        //Beaute Routes
        Route::resource('orders/beautes', 'BeauteController');
        Route::get('api/orders/user/like_beautes/{id}', 'BeauteController@likePost');
        Route::post('orders/beautes/image','ImageController@store');
        Route::get('orders/api/beautes', 'BeauteController@getbeautes');
        Route::get('orders/api/beautes/menucategoryorders', 'BeauteController@menucategoryorder');
        Route::get('orders/api/beautes/categoryorders', 'BeauteController@categoryorder');
        Route::get('orders/api/beautes/colors', 'BeauteController@color');
        Route::get('orders/beautes/topic/{menucategoryorder}', 'BeauteController@getcategory')->name('category.beaute');
        Route::get('orders/beautes/{menucategoryorder}/show/{beaute}', 'BeauteController@view')->name('view.beaute');
        Route::get('/api/orders/user/active_beautes/{id}', 'BeauteController@useractive');
        Route::get('/api/orders/user/disable_beautes/{id}', 'BeauteController@userdisable');

        //Informatiques Routes
        Route::resource('orders/informatiques', 'InformatiquesController');

        //Categoryorder Route
        Route::get('orders/informatiques/topic/{menucategoryorder}', 'InformatiquesController@getcategory')->name('topic.menucategoryorder');
        Route::get('orders/informatiques/{menucategoryorder}/show/{informatique}', 'InformatiquesController@view')->name('view.informatique');
        //Route::get('topics/tag/{tag}', 'InformatiquesController@tag')->name('topic.tag');

    });

    //Comments

app/Http/Controllers/Admin/Sites/OrdersController.php
<?php

namespace App\Http\Controllers\Admin\Sites;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Site/Order/ImageController.php
<?php

namespace App\Http\Controllers\Site\Order;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ImageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/OrdersController.php
<?php

namespace App\Http\Controllers\User;


use App\Model\admin\categories\categoryorder;
use App\Model\admin\slides\slidesorder;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;

class OrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $expiresAt = now()->addSeconds(10);
        $slidesorders = Cache::remember('slidesorders', $expiresAt, function () {
            return Slidesorder::where('status',1)->orderBy('created_at','DESC')->get();
        });
        $categoryorders = categoryorder::where('status',1)->orderBy('created_at')->get();
        return view('site.page.orders',compact('slidesorders','categoryorders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/site/order/informatique/create.blade.php
@extends('inc.app')
@section('title', '- Informatique')
@section('style')


<style type="text/css">

    .main-section{

        margin: 0px;
        padding: 20px;
        margin-top: 100px;
        background-color: #fff;
        box-shadow: 0px 0px #cc0000;
    }
</style>
@endsection
@section('navbar')

@guest
<nav class="navbar navbar-color-on-scroll navbar-transparent    fixed-top  navbar-expand-lg bg-warning" color-on-scroll="100" id="sectionsNav">
    @else
    <nav class="navbar navbar-color-on-scroll navbar-transparent    fixed-top  navbar-expand-lg bg-{{ Auth::user()->color_name }}" color-on-scroll="100" id="sectionsNav">
        @endguest
        @endsection
        @section('content')

<div class="landing-page">

            <div class="page-header header-filter header-small" data-parallax="true" style="background-image: url(&apos;{{ URL::to('assets/img/image.jpg')}}&apos;);">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 ml-auto mr-auto text-center">
                            <h1 class="title">Informatique</h1>
                            <h5 class="title">Set Up your Slide in your Dashboard</h5>
                        </div>
                    </div>
                </div>
            </div>

            <div class="main main-raised">
                <div class="main">
                    <div class="section">
                        <div class="container">


                            @include('inc.alert')

                            <form id="RegisterValidation"  role="form" method="POST" action="{{route('informatiques.store')}}" enctype="multipart/form-data" accept-charset="UTF-8">
                                {{ csrf_field() }}

                                @include('site.order.informatique.form',['informatique' => new \App\Model\user\order\informatique()])

                                <div class="row buttons-row">
                                    <div class="col-md-6 col-sm-6">
                                        <button class="btn btn-outline-danger btn-block btn-round">Cancel</button>
                                    </div>
                                    <div class="col-md-6 col-sm-6">
                                       <button type="submit" class="btn btn-outline-primary btn-block btn-round">Save</button>
                                    </div>
                                    <!--<div class="col-md-4 col-sm-4">
                                        <button class="btn btn-primary btn-block btn-round">Save & Publish </button>
                                    </div>-->
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
</div>
@include('inc._footer')
@endsection

@section('scripts')
@parent



@endsection

resources/views/site/order/informatique/edit.blade.php
@extends('inc.app')
<?php $titleTag = htmlspecialchars($informatique->title); ?>
@section('title',"- edit $titleTag" )

@section('style')
    <script>
        window.Laravel = {!! json_encode([
        'csrfToken' => csrf_token(),
    ]) !!};
    </script>
@endsection
@section('navbar')

    @guest
        <nav class="navbar navbar-color-on-scroll navbar-transparent    fixed-top  navbar-expand-lg bg-warning" color-on-scroll="100" id="sectionsNav">
            @else
                <nav class="navbar navbar-color-on-scroll navbar-transparent    fixed-top  navbar-expand-lg bg-{{ Auth::user()->color_name }}" color-on-scroll="100" id="sectionsNav">
                    @endguest
                    @endsection
                    @section('content')

                        <div class="landing-page">
                            <div class="page-header header-filter header-small" data-parallax="true" style="background-image: url(&apos;{{ URL::to('assets/img/image.jpg')}}&apos;);">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-md-8 ml-auto mr-auto text-center">
                                            <h1 class="title">Informatique</h1>
                                            <h5 class="title">Set Up your Slide in your Dashboard</h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="main main-raised">
                                <div class="main">
                                    <div class="section">
                                        <div class="container">
                                            <h3>Add Product</h3>
                                            {!! Form::model($informatique, ['files'=> 'true','method' => 'PATCH','route' => ['informatiques.update',$informatique->id], 'id' => 'RegisterValidation']) !!}

                                            @include('site.order.informatique.form')
                                                <div class="row buttons-row">
                                                    <div class="col-md-6 col-sm-6">
                                                        <button class="btn btn-outline-danger btn-block btn-round">Cancel</button>
                                                    </div>
                                                    <div class="col-md-6 col-sm-6">
                                                        <button type="submit" class="btn btn-outline-primary btn-block btn-round">Save</button>
                                                    </div>
                                                    <!--<div class="col-md-4 col-sm-4">
                                                        <button class="btn btn-primary btn-block btn-round">Save & Publish </button>
                                                    </div>-->
                                                </div>
                                            {!! Form::close() !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
     @include('inc._footer')
 @endsection

@section('scripts')
@parent

<script>
    var gear;
    var lastPosition;
    var refreshRate = 60; // fps; reduce for less overhead
    var animation = "rotate(*deg)"; // css style to apply [Wildcard is *]
    var link = 0.5; //what to multiply the scrollTop by

    function replace(){
        if(lastPosition != document.body.scrollTop){ // Prevents unnecessary recursion
            lastPosition = document.body.scrollTop; // updates the last position to current
            gear.style.transform = animation.replace("*", Math.round(lastPosition * link)); // applies new style to the gear
        }
    }

    function setup(){
        lastPosition = document.body.scrollTop;
        gear = document.querySelector(".gear");
        setInterval(replace, 1000 / refreshRate); // 1000 / 60 = 16.666... Invokes function "replace" to update for each frame
    }
    window.addEventListener("DOMContentLoaded", setup);

</script>

@endsection

resources/views/site/order/informatique/form.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="row price-row">
            <div class="col-sm-6 row-block">
                {!! Form::select('menucategoryorder_id', old('menucategoryorder_id') ? old('menucategoryorder_id') : $menucategoryorders = DB::table('menucategoryorders')
                ->where('categoryorder_name', 'informatiques')
                ->where('status', 1)->pluck('name','id')
                ,null, ['data-style'=>'select-with-transition', 'class' => 'form-control selectpicker', 'required' => '','title'=> 'Choose Category ...' ])
                !!}
                @if ($errors->has('menucategoryorder_id'))
                <span class="help-block">
                    <strong class="text-danger text-center">{{ $errors->first('menucategoryorder_id') }}</strong>
                </span>
                @endif

            </div>
            <div class="col-sm-6 row-block">
                {!! Form::select('color_name', old('color_name') ? old('color_name') : App\Model\user\partial\color::where('status',1)->pluck('color_name','slug'),null, ['data-style'=>'select-with-transition', 'class' => 'form-control selectpicker', 'required' => '','title'=> 'Choose Color ...' ]) !!}

                @if ($errors->has('color_name'))
                <span class="help-block">
                    <strong class="text-danger text-center">{{ $errors->first('color_name') }}</strong>
                </span>
                @endif
            </div>

        </div>
        <div class="form-group">
            <h6>Title
                <span class="icon-danger">*</span>
            </h6>
            {!! Form::text('title', null, ['id'=>'title','class' => 'form-control border-input', 'placeholder' => 'enter the product name here...', 'required' => 'required']) !!}
            @if ($errors->has('title'))
            <span class="help-block">
                <strong class="text-danger text-center">{{ $errors->first('title') }}</strong>
            </span>
            @endif
        </div>
        <div class="form-group">
            <h6>Tagline
                <span class="icon-danger">*</span>
            </h6>
            <input type="text" class="form-control border-input" placeholder="enter the product tagline here...">
        </div>
        <div class="row price-row">
            <div class="col-md-6">
                <h6>Contact
                    <span class="icon-danger">*</span>
                </h6>
                <div class="input-group border-input">
                    {!! Form::text('phone', null, ['id'=>'phone','class' => 'form-control border-input', 'placeholder' => 'enter the contact phone here...']) !!}
                    @if ($errors->has('phone'))
                    <span class="help-block">
                        <strong class="text-danger text-center">{{ $errors->first('phone') }}</strong>
                    </span>
                    @endif
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fa fa-phone"></i></span>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <h6>Phone</h6>
                <div class="input-group border-input">
                    <input type="text" value="" placeholder="enter phone or email" class="form-control border-input">
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row price-row">
            <div class="col-md-12">
                <div class="col-md-12 ">
                    <h6>Tags
                        <span class="icon-danger">*</span>
                    </h6>
                    <div id="tags">
                        <input type="text" value="{{ old('tags', $informatique->tagsList) }}" name="tags" class="tagsinput form-control{{ $errors->has('tags') ? ' is-invalid' : '' }}" data-role="tagsinput" data-color="rose" placeholder="Tags" >
                        <!-- You can change data-color="rose" with one of our colors primary | warning | info | danger | success -->
                        @if ($errors->has('tags'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('tags') }}</strong>
                            </span>
                        @endif
                    <!-- <div class="tagsinput-add"></div> -->
                        <!-- You can change "tag-primary" with with "tag-info", "tag-success", "tag-warning","tag-danger" -->
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <h6>Description</h6>
            {!! Form::textarea('body', null, ['id'=>'body','class' => 'form-control textarea-limited', 'placeholder' => 'This is a textarea limited to 150 characters.' , 'rows' =>"13", 'maxlength' => "150"]) !!}
            @if ($errors->has('body'))
            <span class="help-block">
                <strong class="text-danger text-center">{{ $errors->first('body') }}</strong>
            </span>
            @endif
            <h5>
                <small>
                    <span id="textarea-limited-message" class="pull-right">150 characters left</span>
                </small>
            </h5>
        </div>
        <div class="form-check">
            <label class="form-check-label pull-right">
                vous pouvez utiliser le
                <a href="https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/" class="text-danger">
                    markdown ici
                </a>

                <span class="form-check-sign"></span>
            </label>
        </div>
    </div>
</div>